# Generated by Django 4.1.3 on 2022-12-01 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("C_name", models.CharField(max_length=50)),
                ("C_coachID", models.CharField(max_length=50)),
                ("C_gamesWon", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Injury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("I_name", models.CharField(max_length=50)),
                ("I_location", models.CharField(max_length=50)),
                ("I_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("P_name", models.CharField(max_length=50)),
                ("P_teamName", models.CharField(max_length=50)),
                ("P_playerNumber", models.CharField(max_length=50)),
                ("P_position", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PP_positionName", models.CharField(max_length=50)),
                ("PP_offense", models.CharField(max_length=50)),
                ("PP_defense", models.CharField(max_length=50)),
                ("PP_specialTeams", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PS_passingYards", models.CharField(max_length=50)),
                ("PS_rushingYards", models.CharField(max_length=50)),
                ("PS_receivingYards", models.CharField(max_length=50)),
                ("PS_numberOfTurnOvers", models.CharField(max_length=50)),
                (
                    "PS_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_stats",
                        to="sports.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("T_name", models.CharField(max_length=50)),
                ("T_teamID", models.CharField(max_length=50)),
                (
                    "coaches",
                    models.ManyToManyField(related_name="teams", to="sports.coach"),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        related_name="teams",
                        through="sports.PlayerStats",
                        to="sports.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TS_totalTouchDowns", models.CharField(max_length=50)),
                ("TS_totalYards", models.CharField(max_length=50)),
                ("TS_rushingYards", models.CharField(max_length=50)),
                ("TS_passingYards", models.CharField(max_length=50)),
                ("TS_turnOvers", models.CharField(max_length=50)),
                (
                    "TS_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_stats",
                        to="sports.team",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="playerstats",
            name="PS_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_stats",
                to="sports.team",
            ),
        ),
        migrations.CreateModel(
            name="PlayerInjuries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date_injured", models.DateField()),
                ("Return_date", models.DateField()),
                (
                    "injury",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_injuries",
                        to="sports.injury",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_injuries",
                        to="sports.player",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="player",
            name="injuries",
            field=models.ManyToManyField(
                related_name="players",
                through="sports.PlayerInjuries",
                to="sports.injury",
            ),
        ),
    ]
