# Generated by Django 4.1.3 on 2022-12-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0002_alter_player_p_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="C_gamesWon",
            field=models.CharField(max_length=50),
        ),
    ]
